#!/usr/bin/env bash

./prepare

bosh sync blobs

cp config/final.yml config/final.yml.bk
cp config/final.yml.local config/final.yml

bosh create release --final --force --with-tarball
cp config/final.yml.bk config/final.yml
rm config/final.yml.bk
